#!/bin/bash
# Created for Trenta.io
# Frostlock takes your current desktop wallpaper, creates a blurred version which is then set as your GDM lockscreen background. 


while true
do
ls -d ~/.cache/wallpaper/* | entr -d convert -blur 0x25 -fill black -colorize 25% ~/.cache/wallpaper/* /usr/share/backgrounds/wallpaper-blur.jpg
done
